spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/boeing
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  redis:
    host: redis
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://bizscanner.store/api/v1/login/oauth2/code/google"
            scope: profile, email

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "https://bizscanner.store/api/v1/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, nickname, email, profile_image
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "https://bizscanner.store/api/v1/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cache:
    ehcache:
      config: ehcache.xml

jwt:
  secretKey: ${JWT_SECRETKEY}
  access:
    expiration: 3600000 # 1시간
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  server:
    port: ${PROMETHEUS_PORT}
    base-path: ${PROMETHEUS_PATH}

server:
  servlet:
    context-path: /api/v1
  tomcat:
    mbeanregistry:
      enabled: true